# Credenciales reales locales (Equivalente al archivo .env)
spring.datasource.url=jdbc:postgresql://localhost:5432/HotelBDD
spring.datasource.username=diegoyanez
spring.datasource.password=1751050913
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuración del ORM para desarrollo
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true